In [5]:
import numpy as np


In [ ]:
np.array([1, 2, 3])
np.zeros((2, 3))  # 2x3 array of zeros
np.ones((3, 3))   # 3x3 array of ones
np.full((2, 2), 7)  # 2x2 array of sevens
np.eye(3)  # 3x3 identity matrix
np.diag([1, 2, 3])  # Diagonal matrix

np.arange(0, 10, 2)  # [0, 2, 4, 6, 8]
np.linspace(0, 1, 5)  # [0. , 0.25, 0.5 , 0.75, 1.]

np.random.rand(3, 2)  # Uniform [0, 1], shape 3x2
np.random.randn(3, 2) # Normal distribution
np.random.randint(0, 10, (3, 3))  # Random integers
np.random.normal(0, 1, (2, 2))  # Mean 0, Std 1

array = np.array([[1, 5, 3], [4, 5, 6], [7, 8, 9]])

array.shape      # Shape of the array
array.ndim       # Number of dimensions
array.size       # Total number of elements
array.dtype      # Data type of elements
array.T
print(np.empty([3, 3], dtype=int))

np.arange(1,10)
np.linspace(1, 10, 3)

arr = np.array([1, 2, 3, 99, 5, 6])  

reshaped = arr.reshape(2, 3)  # Reshape to 2x3  
flattened = arr.ravel()       # Flatten the array  

# Slicing  
subarray = reshaped[1:2, 0:2]  # Get the second row and first two columns  

print("Reshaped array:\n", reshaped)  
print("Flattened array:\n", flattened)  
print("Subarray:\n", subarray)  



[[1 5 3]
 [4 5 6]
 [7 8 9]]
Reshaped array:
 [[ 1  2  3]
 [99  5  6]]
Flattened array:
 [ 1  2  3 99  5  6]
Subarray:
 [[99  5]]


In [ ]:
arr = np.array([1,2,3])
# Element-wise operations
result = arr + 1
result = arr * 2
result = np.sin(arr)

# Reduction operations
total = np.sum(arr)
mean = np.mean(arr)
std = np.std(arr)
max_val = np.max(arr)
argmax = np.argmax(arr)  # Index of max value


6


In [83]:
arr = np.array([1,2,3])
mask = arr > 5             # Boolean array
filtered = arr[arr > 5]    # Filter elements

all_true = np.all(mask)    # Check if all True
any_true = np.any(mask)    # Check if any True

In [ ]:
arr1 = np.array([1,2,3])
arr2= np.array([3,4,5])
dot_product = np.dot(arr1, arr2)  # Dot product
det = np.linalg.det(arr)          # Determinant
eigvals, eigvecs = np.linalg.eig(arr)  # Eigenvalues/vectors
inv = np.linalg.inv(arr)          # Inverse


In [ ]:
# Adding the values at the end 
# of a numpy array 
arr = np.arange(1, 13).reshape(2, 6) 
print("Original Array") 
print(arr, "\n") 

# create another array which is 
# to be appended column-wise 
col = np.arange(5, 11).reshape(1,6)
arr_col = np.append(arr, col, axis=0) 
print("Array after appending the values column wise") 
print(arr_col, "\n") 

# create an array which is 
# to be appended row wise 
row = np.array([1, 2]).reshape(2, 1) 
arr_row = np.append(arr, row, axis=1) 
print("Array after appending the values row wise") 
print(arr_row)


Original Array
[[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]] 

[[ 5  6  7  8  9 10]]
Array after appending the values column wise
[[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]
 [ 5  6  7  8  9 10]] 

Array after appending the values row wise
[[ 1  2  3  4  5  6  1]
 [ 7  8  9 10 11 12  2]]


In [13]:
arr1 = np.array([[2, 4], [6, 8]]) 
arr2 = np.array([[3, 5], [7, 9]]) 

# combining on axis 0 
gfg = np.concatenate((arr1, arr2), axis = 0) 
print(gfg) 

# combining on axis 1 
gfg = np.concatenate((arr1, arr2), axis = 1) 
print("\n", gfg) 

# combining on axis None 
gfg = np.concatenate((arr1, arr2), axis = None) 
print("\n", gfg) 

# stacking two arrays on one another 
print(np.stack((arr1, arr2), axis=1))


[[2 4]
 [6 8]
 [3 5]
 [7 9]]

 [[2 4 3 5]
 [6 8 7 9]]

 [2 4 6 8 3 5 7 9]
[[[2 4]
  [3 5]]

 [[6 8]
  [7 9]]]


In [27]:
url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'

data = np.genfromtxt(url,delimiter=',', dtype='float')
data

array([[5.1, 3.5, 1.4, 0.2, nan],
       [4.9, 3. , 1.4, 0.2, nan],
       [4.7, 3.2, 1.3, 0.2, nan],
       [4.6, 3.1, 1.5, 0.2, nan],
       [5. , 3.6, 1.4, 0.2, nan],
       [5.4, 3.9, 1.7, 0.4, nan],
       [4.6, 3.4, 1.4, 0.3, nan],
       [5. , 3.4, 1.5, 0.2, nan],
       [4.4, 2.9, 1.4, 0.2, nan],
       [4.9, 3.1, 1.5, 0.1, nan],
       [5.4, 3.7, 1.5, 0.2, nan],
       [4.8, 3.4, 1.6, 0.2, nan],
       [4.8, 3. , 1.4, 0.1, nan],
       [4.3, 3. , 1.1, 0.1, nan],
       [5.8, 4. , 1.2, 0.2, nan],
       [5.7, 4.4, 1.5, 0.4, nan],
       [5.4, 3.9, 1.3, 0.4, nan],
       [5.1, 3.5, 1.4, 0.3, nan],
       [5.7, 3.8, 1.7, 0.3, nan],
       [5.1, 3.8, 1.5, 0.3, nan],
       [5.4, 3.4, 1.7, 0.2, nan],
       [5.1, 3.7, 1.5, 0.4, nan],
       [4.6, 3.6, 1. , 0.2, nan],
       [5.1, 3.3, 1.7, 0.5, nan],
       [4.8, 3.4, 1.9, 0.2, nan],
       [5. , 3. , 1.6, 0.2, nan],
       [5. , 3.4, 1.6, 0.4, nan],
       [5.2, 3.5, 1.5, 0.2, nan],
       [5.2, 3.4, 1.4, 0.2, nan],
       [4.7, 3

In [28]:
arr = np.array([[1, 2, 3],
                [4, 5, 6],
                [7, 8, 9]])

# Appliquer la fonction sum sur chaque ligne (axe=1)
result = np.apply_along_axis(np.sum, axis=1, arr=arr)

print(result)

[ 6 15 24]


## Use Cases

- DataFrame:

Ideal for handling tabular data, such as data from CSV files, SQL databases, or Excel spreadsheets. Commonly used in data analysis tasks.

- NumPy Array:

Best suited for numerical computations, mathematical modeling, image processing, and scientific computing.